"""initial schema

Revision ID: 47bfe299fa92
Revises: 
Create Date: 2026-08-26 14:25:23.222825+00:00
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types

revision: str = '47bfe299fa92'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=True),
    sa.Column('actor_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('before', app.db.types.JSONBType(), nullable=True),
    sa.Column('after', app.db.types.JSONBType(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_actor_time', 'audit_events', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_company_time', 'audit_events', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_target', 'audit_events', ['target_type', 'target_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('scope', sa.String(length=96), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', app.db.types.JSONBType(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_records_scope')
    )
    op.create_table('inbox_events',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('payload', app.db.types.JSONBType(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('processed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_events')),
    sa.UniqueConstraint('source', 'external_id', name='uq_inbox_events_source')
    )
    op.create_index('ix_inbox_events_pending', 'inbox_events', ['status', 'created_at'], unique=False)
    op.create_table('media_assets',
    sa.Column('company_id', app.db.types.GUID(), nullable=True),
    sa.Column('uploaded_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('variants', app.db.types.JSONBType(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('delete_after', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('object_key', name=op.f('uq_media_assets_object_key'))
    )
    op.create_index(op.f('ix_media_assets_company_id'), 'media_assets', ['company_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', app.db.types.JSONBType(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('locked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('processed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_events_pending', 'outbox_events', ['status', 'available_at'], unique=False)
    op.create_table('plans',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('billing_period', sa.String(length=16), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_table('provider_events',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload_ref', sa.String(length=255), nullable=True),
    sa.Column('payload_digest', sa.String(length=64), nullable=True),
    sa.Column('received_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('processed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_events')),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_events_provider')
    )
    op.create_table('support_tickets',
    sa.Column('company_id', app.db.types.GUID(), nullable=True),
    sa.Column('author_user_id', app.db.types.GUID(), nullable=False),
    sa.Column('assignee_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_response_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('resolved_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('closed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('sla_due_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets'))
    )
    op.create_index(op.f('ix_support_tickets_company_id'), 'support_tickets', ['company_id'], unique=False)
    op.create_table('suppression_entries',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=True),
    sa.Column('telegram_user_id', app.db.types.BigIntType(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppression_entries')),
    sa.UniqueConstraint('company_id', 'telegram_user_id', name='uq_suppression_entries_company_id')
    )
    op.create_index(op.f('ix_suppression_entries_telegram_user_id'), 'suppression_entries', ['telegram_user_id'], unique=False)
    op.create_table('users',
    sa.Column('telegram_user_id', app.db.types.BigIntType(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('platform_role', sa.String(length=24), nullable=False),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_users_telegram_user_id'))
    )
    op.create_table('companies',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('default_locale', sa.String(length=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('owner_user_id', app.db.types.GUID(), nullable=False),
    sa.Column('logo_media_id', app.db.types.GUID(), nullable=True),
    sa.Column('settings', app.db.types.JSONBType(), nullable=False),
    sa.Column('published_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('suspended_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('suspended_reason', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_companies_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug'))
    )
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('plan_entitlements',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('plan_id', app.db.types.GUID(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_entitlements_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_entitlements')),
    sa.UniqueConstraint('plan_id', 'key', name='uq_plan_entitlements_plan_id')
    )
    op.create_table('sessions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('rotated_from_id', app.db.types.GUID(), nullable=True),
    sa.Column('client', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_used_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_sessions_refresh_token_hash'))
    )
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('ticket_id', app.db.types.GUID(), nullable=False),
    sa.Column('author_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('author_kind', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('fk_ticket_messages_ticket_id_support_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_messages'))
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('document_version', sa.String(length=32), nullable=True),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('context', app.db.types.JSONBType(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_consents'))
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('branches',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('company_id', 'slug', name='uq_branches_company_slug')
    )
    op.create_index(op.f('ix_branches_city'), 'branches', ['city'], unique=False)
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_table('broadcasts',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('audience_filter', app.db.types.JSONBType(), nullable=False),
    sa.Column('audience_size', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('finished_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_broadcasts_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_index(op.f('ix_broadcasts_company_id'), 'broadcasts', ['company_id'], unique=False)
    op.create_table('client_tags',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_client_tags_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_tags')),
    sa.UniqueConstraint('company_id', 'name', name='uq_client_tags_company_id')
    )
    op.create_table('clients',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('phone_raw', sa.String(length=40), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('consent_status', sa.String(length=16), nullable=False),
    sa.Column('consent_updated_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('preferences', app.db.types.JSONBType(), nullable=False),
    sa.Column('anonymized_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_clients_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clients_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_clients_company_user')
    )
    op.create_index('ix_clients_company_phone', 'clients', ['company_id', 'phone_normalized'], unique=False)
    op.create_index('ix_clients_company_status', 'clients', ['company_id', 'status'], unique=False)
    op.create_table('employees',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('role_title', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('takes_appointments', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('rating_sum', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index('ix_employees_company_active', 'employees', ['company_id', 'active'], unique=False)
    op.create_table('entitlement_usage',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('period_start', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('period_end', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('meta', app.db.types.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_entitlement_usage_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlement_usage')),
    sa.UniqueConstraint('company_id', 'key', 'period_start', name='uq_entitlement_usage_company_id')
    )
    op.create_table('memberships',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('permissions', app.db.types.JSONBType(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('activated_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('terminated_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('terminated_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_memberships_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships'))
    )
    op.create_index('ix_memberships_company_status', 'memberships', ['company_id', 'status'], unique=False)
    op.create_index('ix_memberships_user_status', 'memberships', ['user_id', 'status'], unique=False)
    op.create_table('service_categories',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_service_categories_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories'))
    )
    op.create_index(op.f('ix_service_categories_company_id'), 'service_categories', ['company_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('plan_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_period_start', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('current_period_end', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('grace_until', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_customer_ref', sa.String(length=128), nullable=True),
    sa.Column('provider_subscription_ref', sa.String(length=128), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_subscriptions_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('company_id', name=op.f('uq_subscriptions_company_id'))
    )
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=False),
    sa.Column('client_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('starts_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('ends_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('service_starts_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('service_ends_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('title_snapshot', sa.String(length=255), nullable=False),
    sa.Column('client_comment', sa.Text(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('cancelled_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('cancelled_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('price_minor >= 0', name=op.f('ck_appointments_price_non_negative')),
    sa.CheckConstraint('starts_at < ends_at', name=op.f('ck_appointments_interval_ordered')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_appointments_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_appointments_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_appointments_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_appointments_employee_id_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments')),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_appointments_company_idempotency')
    )
    op.create_index('ix_appointments_client', 'appointments', ['client_id', 'starts_at'], unique=False)
    op.create_index('ix_appointments_company_start', 'appointments', ['company_id', 'starts_at'], unique=False)
    op.create_index('ix_appointments_employee_start', 'appointments', ['employee_id', 'starts_at'], unique=False)
    op.create_index('ix_appointments_status_start', 'appointments', ['status', 'starts_at'], unique=False)
    op.create_table('broadcast_recipients',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('broadcast_id', app.db.types.GUID(), nullable=False),
    sa.Column('client_id', app.db.types.GUID(), nullable=False),
    sa.Column('recipient_telegram_id', app.db.types.BigIntType(), nullable=True),
    sa.Column('consent_snapshot', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('sent_at', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], name=op.f('fk_broadcast_recipients_broadcast_id_broadcasts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_broadcast_recipients_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_recipients')),
    sa.UniqueConstraint('broadcast_id', 'client_id', name='uq_broadcast_recipients_broadcast_id')
    )
    op.create_index(op.f('ix_broadcast_recipients_company_id'), 'broadcast_recipients', ['company_id'], unique=False)
    op.create_index('ix_broadcast_recipients_status', 'broadcast_recipients', ['broadcast_id', 'status'], unique=False)
    op.create_table('client_notes',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('client_id', app.db.types.GUID(), nullable=False),
    sa.Column('author_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_notes_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_client_notes_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_notes'))
    )
    op.create_index(op.f('ix_client_notes_client_id'), 'client_notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_notes_company_id'), 'client_notes', ['company_id'], unique=False)
    op.create_table('client_tag_links',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('client_id', app.db.types.GUID(), nullable=False),
    sa.Column('tag_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_tag_links_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_client_tag_links_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['client_tags.id'], name=op.f('fk_client_tag_links_tag_id_client_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_tag_links')),
    sa.UniqueConstraint('client_id', 'tag_id', name='uq_client_tag_links_client_id')
    )
    op.create_index(op.f('ix_client_tag_links_company_id'), 'client_tag_links', ['company_id'], unique=False)
    op.create_table('employee_branches',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_employee_branches_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employee_branches_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_branches_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_branches')),
    sa.UniqueConstraint('employee_id', 'branch_id', name='uq_employee_branches_employee_id')
    )
    op.create_index(op.f('ix_employee_branches_company_id'), 'employee_branches', ['company_id'], unique=False)
    op.create_table('schedule_exceptions',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=True),
    sa.Column('employee_id', app.db.types.GUID(), nullable=True),
    sa.Column('starts_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('ends_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.CheckConstraint('starts_at < ends_at', name=op.f('ck_schedule_exceptions_interval_ordered')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_schedule_exceptions_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_schedule_exceptions_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_schedule_exceptions_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_exceptions'))
    )
    op.create_index('ix_schedule_exceptions_lookup', 'schedule_exceptions', ['company_id', 'employee_id', 'starts_at', 'ends_at'], unique=False)
    op.create_table('services',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=True),
    sa.Column('category_id', app.db.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_before_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_after_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('media_asset_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('buffer_after_minutes >= 0', name=op.f('ck_services_buffer_after_non_negative')),
    sa.CheckConstraint('buffer_before_minutes >= 0', name=op.f('ck_services_buffer_before_non_negative')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_services_duration_positive')),
    sa.CheckConstraint('price_minor >= 0', name=op.f('ck_services_price_non_negative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_services_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_services_category_id_service_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_services_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index('ix_services_company_active', 'services', ['company_id', 'active'], unique=False)
    op.create_table('team_invites',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=True),
    sa.Column('employee_id', app.db.types.GUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('permissions', app.db.types.JSONBType(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('used_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('used_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('revoked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_team_invites_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_team_invites_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_team_invites_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_team_invites_token_hash'))
    )
    op.create_index('ix_team_invites_company_status', 'team_invites', ['company_id', 'status'], unique=False)
    op.create_table('weekly_schedule_rules',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_local_time', sa.Time(), nullable=False),
    sa.Column('end_local_time', sa.Time(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name=op.f('ck_weekly_schedule_rules_weekday_range')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_weekly_schedule_rules_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_weekly_schedule_rules_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_weekly_schedule_rules_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_schedule_rules'))
    )
    op.create_index('ix_weekly_rules_scope', 'weekly_schedule_rules', ['company_id', 'branch_id', 'employee_id', 'weekday'], unique=False)
    op.create_table('appointment_events',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', app.db.types.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=True),
    sa.Column('before', app.db.types.JSONBType(), nullable=True),
    sa.Column('after', app.db.types.JSONBType(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_events_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_appointment_events_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_events'))
    )
    op.create_index('ix_appointment_events_appointment', 'appointment_events', ['appointment_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_appointment_events_company_id'), 'appointment_events', ['company_id'], unique=False)
    op.create_table('appointment_services',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', app.db.types.GUID(), nullable=False),
    sa.Column('service_id', app.db.types.GUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_before_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_after_minutes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_services_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_appointment_services_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointment_services_service_id_services'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_services')),
    sa.UniqueConstraint('appointment_id', 'service_id', 'sort_order', name='uq_appointment_services_appointment_id')
    )
    op.create_index(op.f('ix_appointment_services_company_id'), 'appointment_services', ['company_id'], unique=False)
    op.create_table('employee_services',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('service_id', app.db.types.GUID(), nullable=False),
    sa.Column('price_minor_override', sa.Integer(), nullable=True),
    sa.Column('duration_minutes_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employee_services_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_services_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_employee_services_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_services')),
    sa.UniqueConstraint('employee_id', 'service_id', name='uq_employee_services_employee_id')
    )
    op.create_index(op.f('ix_employee_services_company_id'), 'employee_services', ['company_id'], unique=False)
    op.create_table('notification_jobs',
    sa.Column('company_id', app.db.types.GUID(), nullable=True),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('appointment_id', app.db.types.GUID(), nullable=True),
    sa.Column('broadcast_id', app.db.types.GUID(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=48), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('payload', app.db.types.JSONBType(), nullable=False),
    sa.Column('recipient_telegram_id', app.db.types.BigIntType(), nullable=True),
    sa.Column('scheduled_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('locked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('provider_response_code', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('sent_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('cancelled_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_notification_jobs_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_jobs')),
    sa.UniqueConstraint('idempotency_key', name='uq_notification_jobs_idempotency_key')
    )
    op.create_index('ix_notification_jobs_appointment', 'notification_jobs', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_notification_jobs_company_id'), 'notification_jobs', ['company_id'], unique=False)
    op.create_index('ix_notification_jobs_due', 'notification_jobs', ['status', 'scheduled_at'], unique=False)
    op.create_table('payment_orders',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', app.db.types.GUID(), nullable=True),
    sa.Column('subscription_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_order_ref', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('refunded_minor', sa.Integer(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('paid_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('failed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('amount_minor >= 0', name=op.f('ck_payment_orders_amount_non_negative')),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_payment_orders_appointment_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payment_orders_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payment_orders_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_orders')),
    sa.UniqueConstraint('idempotency_key', name='uq_payment_orders_idempotency_key')
    )
    op.create_index('ix_payment_orders_company_status', 'payment_orders', ['company_id', 'status'], unique=False)
    op.create_table('reviews',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=True),
    sa.Column('appointment_id', app.db.types.GUID(), nullable=False),
    sa.Column('client_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reply_body', sa.Text(), nullable=True),
    sa.Column('reply_author_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('reply_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_reviews_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_reviews_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_reviews_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_reviews_appointment_id'))
    )
    op.create_index('ix_reviews_company_status', 'reviews', ['company_id', 'status'], unique=False)
    op.create_table('schedule_breaks',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('rule_id', app.db.types.GUID(), nullable=False),
    sa.Column('start_local_time', sa.Time(), nullable=False),
    sa.Column('end_local_time', sa.Time(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_schedule_breaks_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['weekly_schedule_rules.id'], name=op.f('fk_schedule_breaks_rule_id_weekly_schedule_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_breaks'))
    )
    op.create_index(op.f('ix_schedule_breaks_company_id'), 'schedule_breaks', ['company_id'], unique=False)
    op.create_index('ix_schedule_breaks_rule', 'schedule_breaks', ['rule_id'], unique=False)
    op.create_table('finance_transactions',
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=True),
    sa.Column('appointment_id', app.db.types.GUID(), nullable=True),
    sa.Column('payment_order_id', app.db.types.GUID(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('reversed_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('reverses_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_finance_transactions_appointment_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_finance_transactions_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_order_id'], ['payment_orders.id'], name=op.f('fk_finance_transactions_payment_order_id_payment_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_transactions'))
    )
    op.create_index('ix_finance_company_date', 'finance_transactions', ['company_id', 'occurred_at'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('order_id', app.db.types.GUID(), nullable=False),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_transaction_ref', sa.String(length=128), nullable=False),
    sa.Column('raw_payload_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('confirmed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('failed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], name=op.f('fk_payment_transactions_order_id_payment_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions')),
    sa.UniqueConstraint('provider', 'provider_transaction_ref', name='uq_payment_transactions_provider')
    )
    op.create_index(op.f('ix_payment_transactions_company_id'), 'payment_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_table('refunds',
    sa.Column('order_id', app.db.types.GUID(), nullable=False),
    sa.Column('transaction_id', app.db.types.GUID(), nullable=True),
    sa.Column('company_id', app.db.types.GUID(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_refund_ref', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('requested_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('approved_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], name=op.f('fk_refunds_order_id_payment_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], name=op.f('fk_refunds_transaction_id_payment_transactions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('provider', 'provider_refund_ref', name='uq_refunds_provider')
    )
    op.create_index(op.f('ix_refunds_company_id'), 'refunds', ['company_id'], unique=False)
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_company_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_company_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('ix_finance_company_date', table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_index('ix_schedule_breaks_rule', table_name='schedule_breaks')
    op.drop_index(op.f('ix_schedule_breaks_company_id'), table_name='schedule_breaks')
    op.drop_table('schedule_breaks')
    op.drop_index('ix_reviews_company_status', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_payment_orders_company_status', table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index('ix_notification_jobs_due', table_name='notification_jobs')
    op.drop_index(op.f('ix_notification_jobs_company_id'), table_name='notification_jobs')
    op.drop_index('ix_notification_jobs_appointment', table_name='notification_jobs')
    op.drop_table('notification_jobs')
    op.drop_index(op.f('ix_employee_services_company_id'), table_name='employee_services')
    op.drop_table('employee_services')
    op.drop_index(op.f('ix_appointment_services_company_id'), table_name='appointment_services')
    op.drop_table('appointment_services')
    op.drop_index(op.f('ix_appointment_events_company_id'), table_name='appointment_events')
    op.drop_index('ix_appointment_events_appointment', table_name='appointment_events')
    op.drop_table('appointment_events')
    op.drop_index('ix_weekly_rules_scope', table_name='weekly_schedule_rules')
    op.drop_table('weekly_schedule_rules')
    op.drop_index('ix_team_invites_company_status', table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_index('ix_services_company_active', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_schedule_exceptions_lookup', table_name='schedule_exceptions')
    op.drop_table('schedule_exceptions')
    op.drop_index(op.f('ix_employee_branches_company_id'), table_name='employee_branches')
    op.drop_table('employee_branches')
    op.drop_index(op.f('ix_client_tag_links_company_id'), table_name='client_tag_links')
    op.drop_table('client_tag_links')
    op.drop_index(op.f('ix_client_notes_company_id'), table_name='client_notes')
    op.drop_index(op.f('ix_client_notes_client_id'), table_name='client_notes')
    op.drop_table('client_notes')
    op.drop_index('ix_broadcast_recipients_status', table_name='broadcast_recipients')
    op.drop_index(op.f('ix_broadcast_recipients_company_id'), table_name='broadcast_recipients')
    op.drop_table('broadcast_recipients')
    op.drop_index('ix_appointments_status_start', table_name='appointments')
    op.drop_index('ix_appointments_employee_start', table_name='appointments')
    op.drop_index('ix_appointments_company_start', table_name='appointments')
    op.drop_index('ix_appointments_client', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_service_categories_company_id'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index('ix_memberships_user_status', table_name='memberships')
    op.drop_index('ix_memberships_company_status', table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('entitlement_usage')
    op.drop_index('ix_employees_company_active', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_clients_company_status', table_name='clients')
    op.drop_index('ix_clients_company_phone', table_name='clients')
    op.drop_table('clients')
    op.drop_table('client_tags')
    op.drop_index(op.f('ix_broadcasts_company_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_city'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index('ix_sessions_user_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('plan_entitlements')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppression_entries_telegram_user_id'), table_name='suppression_entries')
    op.drop_table('suppression_entries')
    op.drop_index(op.f('ix_support_tickets_company_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_table('provider_events')
    op.drop_table('plans')
    op.drop_index('ix_outbox_events_pending', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_media_assets_company_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_inbox_events_pending', table_name='inbox_events')
    op.drop_table('inbox_events')
    op.drop_table('idempotency_records')
    op.drop_index('ix_audit_events_target', table_name='audit_events')
    op.drop_index('ix_audit_events_company_time', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_time', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
